# Reshaping

In [1]:
import numpy as np

In [2]:
paises_uno = ('Ecuador','USA','Cuba','Venezuela') 

In [3]:
paises_dos = ('Brazil','China','Japon','Mexico') 

In [5]:
arreglo_paises_2d = np.array([paises_uno,paises_dos]) 

In [6]:
arreglo_paises_2d 

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [7]:
arreglo_paises_2d.shape #Dimensiones

(2, 4)

In [8]:
#Transformar un arreglo de n dimensiones en una sola dimension

In [10]:
arreglo_paises_2d.flatten()  

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brazil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [11]:
arreglo_paises_2d.shape 

(2, 4)

In [12]:
#Dividir el arreglo despues de hacerlo de una sola dimension

In [13]:
arreglo_paises_2d.flatten().reshape(2,2,2) 

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brazil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [ ]:
#Dividir el arreglo en lo que logre llenar

In [14]:
arreglo_paises_2d.flatten().reshape(4,-1) 

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brazil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [ ]:
#Primero que sea lo que sea se autocalcule o en cualquier dimension

In [15]:
arreglo_paises_2d.flatten().reshape(2,2,-1) 

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brazil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [16]:
arreglo_paises_2d.flatten().reshape(-1,2)  

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brazil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [ ]:
#La transpuesta

In [17]:
arreglo_paises_2d 

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [18]:
arreglo_paises_2d.T.shape 

(4, 2)

In [19]:
arreglo_paises_2d.T.flatten() 

array(['Ecuador', 'Brazil', 'USA', 'China', 'Cuba', 'Japon', 'Venezuela',
       'Mexico'], dtype='<U9')

In [ ]:
#Spliting

In [ ]:
#Crear otra variable y guardarlo como una dimension

In [20]:
arreglo_paises = arreglo_paises_2d.flatten()

In [21]:
arreglo_paises

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brazil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [ ]:
#split divide el arreglo

In [22]:
np.split(arreglo_paises,2)

[array(['Ecuador', 'USA', 'Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brazil', 'China', 'Japon', 'Mexico'], dtype='<U9')]

In [23]:
np.split(arreglo_paises,4) 

[array(['Ecuador', 'USA'], dtype='<U9'),
 array(['Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brazil', 'China'], dtype='<U9'),
 array(['Japon', 'Mexico'], dtype='<U9')]

In [24]:
arreglo = np.arange(12)

In [25]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#Dividir el arreglo

In [26]:
np.split(arreglo,2) 

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [ ]:
#Dividir arreglo por indices donde se corta para dividir

In [27]:
np.split(arreglo,[1,3,5,7,8]) 

[array([0]),
 array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7]),
 array([ 8,  9, 10, 11])]

In [ ]:
#Horizontal split

In [32]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [33]:
np.hsplit(arreglo_paises_2d,2) 

[array([['Ecuador', 'USA'],
        ['Brazil', 'China']], dtype='<U9'), array([['Cuba', 'Venezuela'],
        ['Japon', 'Mexico']], dtype='<U9')]

In [ ]:
#Vertical Split y el split normal son iguales

In [30]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [31]:
np.vsplit(arreglo_paises_2d,2) 

[array([['Ecuador', 'USA', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')]

In [34]:
np.split(arreglo_paises_2d,2) 

[array([['Ecuador', 'USA', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')]

In [ ]:
# Guardar en distintas variables

In [35]:
np.hsplit(arreglo_paises_2d,4) 

[array([['Ecuador'],
        ['Brazil']], dtype='<U9'), array([['USA'],
        ['China']], dtype='<U9'), array([['Cuba'],
        ['Japon']], dtype='<U9'), array([['Venezuela'],
        ['Mexico']], dtype='<U9')]

In [36]:
arr1,arr2,arr3,arr4 = np.hsplit(arreglo_paises_2d,4) 

In [37]:
arr1 

array([['Ecuador'],
       ['Brazil']], dtype='<U9')

In [38]:
type(np.hsplit(arreglo_paises_2d,4)) 

list

In [39]:
x1,x2,x3 = [1,2,3] 

In [40]:
x1 = x2 = x3 = 1 # Para que todas las variables tengan el mismo valor

In [41]:
x1 = x1 + 1 

In [42]:
x1

2

In [43]:
x2 

1