# Indices 

In [1]:
import numpy as np 

In [4]:
numeros = np.arange(11)**2  

In [5]:
numeros 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
indeces = [2,5,7] 

In [9]:
numeros [indeces] 

array([ 4, 25, 49])

In [11]:
arreglo_frutas = np.array ([['Piña','Manzana','Pera','Melon'],
                           ['Pera','Uva','Naranja','Papaya'],
                           ['Frutilla','Platano','Granadilla','Sandia']])


In [12]:
arreglo_frutas.shape 

(3, 4)

In [23]:
arreglo_fila = np.array([
                           [0,0],
                           [1,1],
                           [2,2],
                          ])

In [24]:
arreglo_columnas = np.array([
                                [1,3],
                                [1,2],
                                [0,2],
                             ])

In [26]:
arreglo_frutas = np.array ([['Piña','Manzana','Pera','Melon'],
                           ['Pera','Uva','Naranja','Papaya'],
                           ['Frutilla','Platano','Granadilla','Sandia']])

In [27]:
arreglo_frutas[arreglo_fila,arreglo_columnas] 

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Granadilla']], dtype='<U10')

In [28]:
arreglo_fila = np.array([
                           [0,0],
                           [1,1],
                           [2,2],
                          ])

arreglo_columnas = np.array([
                                [2,3],
                                [2,3],
                                [2,3],
                             ]) 

In [30]:
arreglo_frutas [arreglo_fila,arreglo_columnas] 

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Granadilla', 'Sandia']], dtype='<U10')

In [31]:
arreglo_fruta = np.array ([['Piña','Manzana','Pera'],
                           ['Pera','Uva','Naranja'],
                           ['Frutilla','Platano','Granadilla'],
                           ['Melon','Platano','Granadilla']])

In [32]:
arreglo_fruta

array([['Piña', 'Manzana', 'Pera'],
       ['Pera', 'Uva', 'Naranja'],
       ['Frutilla', 'Platano', 'Granadilla'],
       ['Melon', 'Platano', 'Granadilla']], dtype='<U10')

In [33]:
arreglo_fila = np.array([
                           [0,0],
                           [1,1],
                           [2,2],
                          ])

arreglo_columnas = np.array([
                            [2,3],
                            [2,3],
                            [2,3],
                             ]) 

In [34]:
arreglo_fruta [arreglo_fila,arreglo_columnas] 

array([['Piña', 'Pera'],
       ['Pera', 'Naranja'],
       ['Frutilla', 'Granadilla'],
       ['Melon', 'Granadilla']], dtype='<U10')

In [53]:
arreglo_fruta2 = np.array ([['Piñas','Manzana','Pera','Naranja'],
                           ['Pera','Uva','Naranja','Melo'],
                           ['Frutilla','Platano','Granadilla','Sandia'],
                           ['Melon','Platano','Granadilla','Limon'],
                           ['Piña','Manzana','Pera','Naranja'],
                           ['Pera','Uva','Naranja','Melo'],
                          ])

In [54]:
arreglo_fruta2.shape = (3,4,2) 

In [55]:
arreglo_fruta2 

array([[['Piñas', 'Manzana'],
        ['Pera', 'Naranja'],
        ['Pera', 'Uva'],
        ['Naranja', 'Melo']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Melon', 'Platano'],
        ['Granadilla', 'Limon']],

       [['Piña', 'Manzana'],
        ['Pera', 'Naranja'],
        ['Pera', 'Uva'],
        ['Naranja', 'Melo']]], dtype='<U10')

In [56]:
arreglo_fruta2 [0][0][0]  

'Piñas'

In [60]:
arreglo_fruta2 [0][3][1] 

'Melo'

In [74]:
arreglo_fruta2 [0][[0,0]][[0,1]] 

array([['Piñas', 'Manzana'],
       ['Piñas', 'Manzana']], dtype='<U10')

In [70]:
arreglo_frutas[np.array([0]),np.array([0,1])] 

array(['Piña', 'Manzana'], dtype='<U10')

In [79]:
arreglo_fruta2[np.array([0]),np.array([0,1]),np.array([0,1])]  

array(['Piñas', 'Naranja'], dtype='<U10')

In [80]:
primer_dimension = np.array (
                            [0,0,0]
                           )

segunda_dimension = np.array (
                            [0,0,0]
                            )

tercera_dimension = np.array (
                            [0,1,0]
                            )

In [81]:
arreglo_fruta2[primer_dimension,segunda_dimension,tercera_dimension] 

array(['Piñas', 'Manzana', 'Piñas'], dtype='<U10')

In [82]:
arreglo_fruta2[primer_dimension,segunda_dimension,tercera_dimension] ='Nika'

In [83]:
arreglo_fruta2 

array([[['Nika', 'Nika'],
        ['Pera', 'Naranja'],
        ['Pera', 'Uva'],
        ['Naranja', 'Melo']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Melon', 'Platano'],
        ['Granadilla', 'Limon']],

       [['Piña', 'Manzana'],
        ['Pera', 'Naranja'],
        ['Pera', 'Uva'],
        ['Naranja', 'Melo']]], dtype='<U10')

In [90]:
arreglo_diez = np.arange(10)  

In [91]:
arreglo_mayor = arreglo_diez > 5 

In [92]:
arreglo_diez [arreglo_mayor] 

array([6, 7, 8, 9])

In [94]:
arraeglo_filas

TypeError: 'arreglo_fruta' is an invalid keyword argument for print()