# Encontrar todas las frutas del arreglo que empiecen con P

In [4]:
# Muestra en una sola dimension todas las frutas que empiezan con P con strartwith (Empieza por)
import numpy as np 

In [30]:
arreglo_fruta2 = np.array ([['Piñas','Manzana','Pera','Naranja'],
                           ['Pomelo','Uva','Naranja','Melo'],
                           ['Frutilla','Platano','Granadilla','Sandia'],
                           ['Melon','Papaya','Granadilla','Limon'],
                           ['Piña','Manzana','Pitajaya','Naranja'],
                           ['Lima','Uva','Naranja','Melo'],
                          ]) 

In [31]:
arreglo_fruta2.shape = (3,4,2) 

In [33]:
arreglo_fruta2  

array([[['Piñas', 'Manzana'],
        ['Pera', 'Naranja'],
        ['Pomelo', 'Uva'],
        ['Naranja', 'Melo']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Melon', 'Papaya'],
        ['Granadilla', 'Limon']],

       [['Piña', 'Manzana'],
        ['Pitajaya', 'Naranja'],
        ['Lima', 'Uva'],
        ['Naranja', 'Melo']]], dtype='<U10')

In [34]:
arreglo_fruta2.flatten() 

array(['Piñas', 'Manzana', 'Pera', 'Naranja', 'Pomelo', 'Uva', 'Naranja',
       'Melo', 'Frutilla', 'Platano', 'Granadilla', 'Sandia', 'Melon',
       'Papaya', 'Granadilla', 'Limon', 'Piña', 'Manzana', 'Pitajaya',
       'Naranja', 'Lima', 'Uva', 'Naranja', 'Melo'], dtype='<U10')

In [35]:
inicio_nombreP = np.array([fruta.startswith('P') for fruta in arreglo_fruta2.flatten()]) 

In [36]:
inicio_nombreP 

array([ True, False,  True, False,  True, False, False, False, False,
        True, False, False, False,  True, False, False,  True, False,
        True, False, False, False, False, False])

In [37]:
arreglo_fruta2.flatten()[inicio_nombreP]  

array(['Piñas', 'Pera', 'Pomelo', 'Platano', 'Papaya', 'Piña', 'Pitajaya'],
      dtype='<U10')

# Mostrar un arreglo de 3, 4, 2 

In [38]:
# Mostrar los un array de 3dimensiones

In [57]:
array_numeros3d = np.arange(24).reshape(3,4,2) 

In [58]:
array_numeros3d 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [54]:
primera_dim = np.array([
    [[0,0]],
    [[1,1]],
    [[2,2]],
])
primera_dim.shape 

segunda_dim = np.array([
    [[0,0],
    [1,1],
    [2,2],
    [3,3]]
])
segunda_dim.shape

tercera_dim = np.array([
    [0,1]
])
tercera_dim.shape 

(1, 2)

In [55]:
arreglo_fruta2[primera_dim, segunda_dim, tercera_dim] 

array([[['Piñas', 'Manzana'],
        ['Pera', 'Naranja'],
        ['Pomelo', 'Uva'],
        ['Naranja', 'Melo']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Melon', 'Papaya'],
        ['Granadilla', 'Limon']],

       [['Piña', 'Manzana'],
        ['Pitajaya', 'Naranja'],
        ['Lima', 'Uva'],
        ['Naranja', 'Melo']]], dtype='<U10')

In [59]:
array_numeros3d[primera_dim, segunda_dim, tercera_dim] 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])